### ISSUE TITLE
Stack Trace Details?

### ISSUE THREAD

**Issue by richgoldmd** [fulcrumapp/v8-sandbox#14]
When a userland script throws an error, the object stack trace only contains a text summary of the error. Any way to get a detailed stack trace? Line number, etc?

Thanks  for a great project.

**Comment by CyberPhoenix90** [comment]
you can use sandbox.shutdown(); to achieve the desired effect and use any method you want to decide how long to wait before you call it

**Comment by zhm** [comment]
I did try hard to figure out how to do this, but I never was able to figure it out. It's possible v8 has since been updated to support this in the API.

If anyone would like to look into this more, the relevant code is here: https://github.com/fulcrumapp/v8-sandbox/blob/46e192b983ea45e6ac83f5ca2607bf9efc046f53/src/sandbox.cc#L267-L276
